version: '2.2.3'
services:
  awesome-creator:
    image: awesome-creator
    build: .
    command: yarn dev
    depends_on:
      - postgresql
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
  postgresql:
    container_name: "postgresql"
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
       - postgres_persist:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - default

networks:
  default:
volumes:
  postgres_persist : {}
  node_modules: {}

# Volumes => refletir diretórios
